repositories:
  - name: crossplane-stable
    url: https://charts.crossplane.io/stable
releases:
  - chart: crossplane-stable/crossplane
    cleanupOnFail: false
    devel: false
    name: crossplane
    skipDeps: false
    createNamespace: true
    namespace: crossplane-system
    kubeContext: adam-example
  - chart: ./manifests/provider/
    name: provider-terraform
    namespace: crossplane-system
    strategicMergePatches:
      - apiVersion: pkg.crossplane.io/v1alpha1
        kind: ControllerConfig
        metadata:
          name: terraform-config
          namespace: crossplane-system
          annotations:
            eks.amazonaws.com/role-arn: {{ requiredEnv "AWS_ROLE_ARN" }}