# permissions for end users to edit modules.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: module-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: adam-controller-manager
    app.kubernetes.io/part-of: adam-controller-manager
    app.kubernetes.io/managed-by: kustomize
  name: module-editor-role
rules:
- apiGroups:
  - adam.k8s.yardbirdsax.github.io
  resources:
  - modules
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - adam.k8s.yardbirdsax.github.io
  resources:
  - modules/status
  verbs:
  - get
